/**
 * Server-side only. Importing this module from a Client Component ships a live Postgres
 * connection string and Firebase Admin credentials into the browser bundle — that is a
 * Principle II violation (ask eligibility must be computed and enforced on the server;
 * a client that can read this module's internals can forge its own authority).
 *
 * Two data paths live here on purpose:
 *  - `db.query` is the native-SQL escape hatch (data-model.md "Selection query"): a direct
 *    Postgres connection for statements GraphQL's declarative query surface cannot express
 *    (correlated NOT EXISTS, a relational COUNT driving ORDER BY). It talks to the same
 *    Postgres instance Firebase SQL Connect provisions.
 *  - `findParticipantById` / `createParticipant` / `getQuestionById` are SQL Connect's
 *    generated Admin Node SDK operations (dataconnect/connector/*.gql), typed and
 *    server-deployed. Prefer these for plain CRUD; reach for `db.query` only when the
 *    generated surface cannot say what you need in one round trip.
 */
import 'server-only';

// Generated by `firebase dataconnect:sdk:generate` from dataconnect/connector/*.gql
// (connector.yaml's adminNodeSdk target: src/db/dataconnect-generated). Imported by its
// package name, not a relative path — the deep build files it ships carry no standalone
// type declarations, only the package root does. Requires
// "@happen-to-have/dataconnect-generated" to be linked into package.json (file: or
// workspace dependency) once that file exists.
import { connectorConfig } from '@happen-to-have/dataconnect-generated';
import { getApps, initializeApp } from 'firebase-admin/app';
import { type DataConnect, getDataConnect } from 'firebase-admin/data-connect';
import { Pool, type QueryResultRow, types } from 'pg';

// node-postgres returns bigint (OID 20 — COUNT(*), COUNT(col)) as a string by default,
// since it cannot safely widen every int8 into a JS number. Every COUNT in this feature
// stays well inside Number.MAX_SAFE_INTEGER, so parse it eagerly: callers get a plain
// number without every query needing its own ::int cast.
types.setTypeParser(20, (value: string) => Number.parseInt(value, 10));

export type {
  Answer_Key,
  CreateParticipantData,
  FindParticipantByIdData,
  FindParticipantByIdVariables,
  GetQuestionByIdData,
  GetQuestionByIdVariables,
  Participant_Key,
  Question_Key,
} from '@happen-to-have/dataconnect-generated';
export {
  connectorConfig,
  createParticipant,
  findParticipantById,
  getQuestionById,
  QuestionStatus,
} from '@happen-to-have/dataconnect-generated';

// The emulator has no SSL and no real credentials; `firebase-admin` detects it from this
// env var. DATACONNECT_EMULATOR_HOST is this repo's name for it (.env.example) — bridged
// here rather than renamed, so every other file can keep the one name.
const emulatorHost = process.env.DATACONNECT_EMULATOR_HOST;
if (emulatorHost && !process.env.DATA_CONNECT_EMULATOR_HOST) {
  process.env.DATA_CONNECT_EMULATOR_HOST = emulatorHost;
}

let dataConnect: DataConnect | undefined;

/** The Firebase SQL Connect Admin client, lazily initialized once per server process. */
export function getConnector(): DataConnect {
  if (!dataConnect) {
    const app = getApps()[0] ?? initializeApp();
    dataConnect = getDataConnect(connectorConfig, app);
  }
  return dataConnect;
}

let pool: Pool | undefined;

function getPool(): Pool {
  if (pool) {
    return pool;
  }
  const connectionString = process.env.DATABASE_URL;
  if (!connectionString) {
    // Never default a production connection string. The emulator is the one environment
    // allowed to fall back, and only because DATACONNECT_EMULATOR_HOST already marks it.
    if (!emulatorHost) {
      throw new Error(
        'DATABASE_URL is required outside the SQL Connect emulator. Refusing to guess a ' +
          'connection string.',
      );
    }
    pool = new Pool({
      connectionString: 'postgres://127.0.0.1:5432/happen_to_have?sslmode=disable',
    });
    return pool;
  }
  pool = new Pool({ connectionString });
  return pool;
}

/**
 * Direct Postgres access for native-SQL queries. Every caller must use parameterized
 * placeholders ($1, $2, ...) — never string-interpolate a value into `sql`.
 */
export const db = {
  query<T extends QueryResultRow = QueryResultRow>(
    sql: string,
    params?: readonly unknown[],
  ): Promise<{ rows: T[] }> {
    return getPool().query<T>(sql, params as unknown[] | undefined);
  },
};
